### ISSUE TITLE
Company List

### ISSUE THREAD

**Issue by leerob** [leerob/dsmtech#3]
Here's some companies that have been mentioned, but I haven't got around to verifying/adding. 

- TekSystems
- ITA Group
- Fastpath
- Robert Half
- Palmer Group
- Businessolver
- eWay Corp
- Spindustry
- Booz Allen Hamilton
- General Dynamics IT
- Aureon
- Mediacom
- Centurylink
- Unity Point
- Caseys
- [web-agencies-worldwide/iowa.md at master · kjbrum/web-agencies-worldwide · GitHub](https://github.com/kjbrum/web-agencies-worldwide/blob/master/agencies/north-america/united-states/iowa.md?fbclid=IwAR1SqJZujIjNP3HLdFeHauxQAx1nrHNayI5h3vTvT2RxYPg36B38DjggeJI#des-moines)

**Comment by dustyjuhl** [comment]
AgencyBloc is an InsurTech startup located in "Des Moines" (I don't have an exact address).

CATEGORY: Startup

Description: AgencyBloc is an agency management system that helps life and health insurance agencies grow their business with an industry-specific CRM, commissions processing, and integrated business and marketing automation.

SOCIAL LINKS: [linkedin](http://www.linkedin.com/company/agencybloc) -- [facebook](https://www.facebook.com/agencybloc) -- [twitter](https://twitter.com/agencybloc)

CAREERS PAGE: https://www.agencybloc.com/company/careers/

LOGO: 
![agencybloc-logo](https://user-images.githubusercontent.com/6274624/67984634-28b4af00-fbf5-11e9-9f0c-f95c1f91b217.png)

**Comment by dustyjuhl** [comment]
Businessolver

CATEGORY: Private

Description: We deliver benefits administration solutions and services you and your employees need for today and tomorrow, transforming the annual enrollment experience into a year-round personalized journey.

SOCIAL LINKS: [linkedin](https://www.linkedin.com/company/businessolver/) -- [facebook](https://www.facebook.com/bsolver) -- [twitter](https://twitter.com/businessolver) -- [instagram](https://www.instagram.com/businessolver/)

CAREERS PAGE: https://www.businessolver.com/who-we-are/careers
