### ISSUE TITLE
Company request template.

### ISSUE THREAD

**Issue by leerob** [leerob/dsmtech#4]
To add a new company, this information is needed: 

- Company Category (private? public? startup?)
- Description (Bio)
- Social links (FB, Twitter, Instagram, LinkedIn)
- Careers page 
- Preferred images to use for the company card - maybe of the office or of some employees.
- Logo
- Company address

[Here's the actual file](https://github.com/leerob/dsmtech/blob/master/companies.js) that gets modified.

**Comment by njoens** [comment]
**CATEGORY**:    Startup

**Description**:    Structurely builds industry-leading artificial intelligence lead engagement software for top producing real estate organizations, including the likes of RE/MAX, Keller Williams, Berkshire Hathaway Home Services, eXp Realty, and more leading teams.

**SOCIAL LINKS**:    [linkedin](https://www.linkedin.com/company/10822430) -- [facebook](https://www.facebook.com/structurely) -- [twitter](https://twitter.com/structurelyre) -- [instagram](https://www.instagram.com/structurely)

**CAREERS PAGE**:    https://structurely.recruitee.com/

**CARD IMAGE**:    
![careers-header](https://user-images.githubusercontent.com/13541378/52892641-eb3cee00-3159-11e9-874b-8cce2eff44ff.png)

**LOGO**:    
![structurely-green-logo-icon](https://user-images.githubusercontent.com/13541378/52892644-f8f27380-3159-11e9-93dc-12f92584cb61.png)

**ADDRESS**: 232 Main St, Ames IA 50010

**Comment by leerob** [comment]
@njoens Thank you! I will get this added in the next batch.

**Comment by njoens** [comment]
hey @leerob will you be updating the site soon? Thanks again!

**Comment by leerob** [comment]
Hey! I haven't forgotten about this. Waiting until I have one more company to add such that company additions happen evenly (as to not mess with the layout).

**Comment by leerob** [comment]
@njoens Done, finally! 😅
