### ISSUE TITLE
Inconsistent font weights on mobile

### ISSUE THREAD

**Issue by T1LT** [leerob/dsmtech#40]
When using larger font weights of Geist, there is an inconsistent behavior when viewed on desktop vs. when viewed on mobile.

The original issue is referenced [here](https://github.com/vercel/geist-font/issues/65).

The fix for it, as mentioned by @diegohaz [here](https://github.com/vercel/geist-font/issues/65#issuecomment-1837402864) is to disable font-synthesis-weight in the global.css file or import the font from the deprecated path `geist/font`

![font-weight-bug](https://github.com/leerob/dsmtech/assets/65653163/518383fe-bbd2-4a45-ae4c-0997594399bc)

**Comment by T1LT** [comment]
@leerob I recently fixed this issue on my portfolio website and I can create a PR if you want me to quickly fix it!

**Comment by leerob** [comment]
Open to a PR, thank you!

**Comment by T1LT** [comment]
@leerob Evil Rabbit has a fix ready but it hasn't been shipped yet - [source](https://x.com/evilrabbit_/status/1744801545550533051?s=20)
I can close the issue if you want me to.

**Comment by T1LT** [comment]
looks like the fix has been merged! closing this issue.
