### ISSUE TITLE
Hatchlings

### ISSUE THREAD

**Issue by yeldarby** [leerob/dsmtech#7]
Would love to get [Hatchlings](https://about.hatchlings.com) added.

**Category:** Startup
**Description:** Hatchlings makes social games for Facebook, iOS, and Android and has entertained over 10 million players since being founded in 2008.
**Careers Page:**  https://careers.hatchlings.com/
**Facebook:** https://facebook.com/hatchlings
**Twitter:** https://twitter.com/hatchlings

Logo attached.

Please let me know if there's anything else you need from us!
![hatchlings_logo_4color](https://user-images.githubusercontent.com/870796/64213252-6f8e5e80-ce69-11e9-867c-b8099b1c7643.png)

**Comment by leerob** [comment]
Yeah, absolutely!

**Comment by leerob** [comment]
Done!
